initial_epsilon: 1.0
final_epsilon: 0.01
epsilon_decay: 0.99816  

lr: 0.0003              
batch_size: 64
memory_size: 50000
target_update_freq: 100

num_episodes: 3000
save_interval: 100
gamma: 0.99
